### ISSUE TITLE
1D histogram of hight - difference between png and hist file

### ISSUE THREAD

**Issue by KatkaJarkovska** [lmareksla/DPE_Issues#14]
### feature/issue description
In the folder Output\Hist, the histogram saved in Hist1D_H_Total.hist is not the same as the histogram showed in Hist1D_H_Total.png. This is seen in the Example (from wiki) as well as in other independent DPE run. 

### program and data specification
**DPE version:**   Version: 1.1.0  21/06/2023
**data type:**   t3pa in the Example from wiki, clog in the other DPE run
**pc configuration:**  windows 11 Pro

### issue originator
Katerina Sykorova

### how to reproduce
example from wiki with clog

### solution description
*describe the solution fixing the issue, put the link to the commit*

### tests
*describe the test procedure, put the link to the protocol if any*

### issue process
- [ ] reproduced   
- [ ] solution / root cause discovered    
- [ ] solution /fix implemented   
- [ ] tested

**Comment by lmareksla** [comment]
There is an additional option to rebin all 1d histograms before visualization: `Hist1DGraphicsRebin = true` (set to false)
Could you please confirm that this is might be the issue or give me more details?

**Comment by KatkaJarkovska** [comment]
I can confirm that the Hist1DGraphicsRebin option seems to be an issue. 

-  If Hist1DGraphicsRebin = 0 (default), the counts for Hight values from Hist1D_H_Total.hist correspond to the histogram shown in Hist1D_H_Total.png.
-  If Hist1DGraphicsRebin = 100 (default), the counts for Hight values from Hist1D_H_Total.hist do not correspond to the histogram shown in Hist1D_H_Total.png. Hist1D_H_Total.hist in this case gives Hight values as if Hist1DGraphicsRebin = 0.

This was tested on the Example from wiki.
