### ISSUE TITLE
Hist - same names of LET and E histograms in all hit plot

### ISSUE THREAD

**Issue by CristinaOanceaADV** [lmareksla/DPE_Issues#87]
### feature/issue description
The histogram with cluster LET appears twice but with different values in the histograms,
rename it to distinguish between the 2 graphs.
Hist from right corresponds to LET column from elist. 
![image](https://github.com/lmareksla/DPE_Issues/assets/143408668/77411e64-75e5-4e1c-9a6a-2dcceba04e9b)

program and data specification
DPE version: DPE_Windows_1.1.0_230831_84a49824
data type: t3pa
used settings of DPE: Standard
pc configuration: *windows10

issue originator
Cristina Oancea (ADVACAMTester)

how to reproduce
working issue 081

solution description
rename hist left or delete it

tests
see Working

### issue process
- [x] reproduced   
- [x] solution / root cause discovered    
- [x] solution /fix implemented   
- [x] tested

**Comment by lmareksla** [comment]
hi, know about it
both of them are correct: one is with fixed binning and the other one is with variable binning (each bin has different width)
the same staff is also with the first two histograms for energy

**Comment by CristinaOanceaADV** [comment]
Thanks for clarifying it. Now I remember about this.
